uwsgi:
    socket: /tmp/telebaka.sock
    module: telebaka.wsgi:application
    master: true
    processes: 4
    enable-threads: true
    venv: /srv/apps/telebaka/venv
    chdir: /srv/apps/telebaka
    hook-post-app: exec:/srv/apps/telebaka/venv/bin/python manage.py set_webhooks
